apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: tlsoff
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
{{- with (first .Values.ingress.hosts) }}
      match: Host(`{{ .host }}`) && (PathPrefix(`/`))
{{- end }}
      services:
        - name: whoami
          port: 80
#  tls: # This route uses TLS
#    secretName: traefik-tls-cert
#  tls:
#    enabled: true
