apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-traefik-ingress
  namespace: tlsoff
  annotations:
    networking.gke.io/managed-certificates: tls-cert-off
    kubernetes.io/ingress.class: gce # Although deprecated by kubernetes spec, GKE still uses this, so must be used
    traefik.ingress.kubernetes.io/frontend-entry-points: "https"
    kubernetes.io/ingress.global-static-ip-name: "traefik-lb-static-ip"
    #networking.gke.io/v1beta1.FrontendConfig: "tftst"
spec:
  defaultBackend:
    service:
      name: traefik
      port:
        number: 80
